# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2017, 9, 10, 17, 14, 26, 814694, tzinfo=utc))),
                ('expires_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
