# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 07:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170911_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default='Others', max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 9, 11, 7, 36, 36, 158216, tzinfo=utc)),
        ),
    ]
