# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20170911_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='unit',
            field=models.CharField(default='units', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 9, 11, 16, 53, 1, 212618, tzinfo=utc)),
        ),
    ]
